# Generated by Django 5.0.6 on 2024-07-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(null=True)),
                ('remove', models.BooleanField(default=False)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
